[package]
name = "tinyrenderer"
version = "0.1.0"
authors = ["Stian Soltvedt <soltvedt.stian@gmail.com>"]
publish = false
edition = "2018"

[dependencies]
conrod = {version = "0.61", features = ["winit", "glium"]}
rand = "0.6"
